export type ErrorCode =
  | 'EMPLOYER_TYPE_NOT_FOUND'
  | 'EMPLOYER_TYPE_SLUG_TAKEN'
  | 'VALIDATION_ERROR'
  | 'UNAUTHORIZED'
  | 'FORBIDDEN'
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'RATE_LIMITED'
  | 'CAPTCHA_REQUIRED'
  | 'CAPTCHA_FAILED'
  | 'INTERNAL_ERROR'
  | 'EMAIL_IN_USE'
  | 'INVALID_CREDENTIALS'
  | 'ACCOUNT_SUSPENDED'
  | 'INVALID_OTP'
  | 'INVALID_TOKEN'
  | 'INVALID_REFRESH_TOKEN'
  | 'EMAIL_NOT_VERIFIED'
  | 'WORKER_NOT_FOUND'
  | 'DOCUMENT_NOT_FOUND'
  | 'PROFILE_INCOMPLETE'
  | 'SUBMISSION_NOT_CANCELLABLE'
  | 'SUBMISSION_NOT_ALLOWED'
  | 'PROFILE_SECTION_LOCKED'
  | 'EDIT_REQUEST_NOT_ALLOWED'
  | 'STORAGE_UNAVAILABLE'
  | 'STORAGE_OBJECT_EMPTY'
  | 'UNSUPPORTED_MEDIA_TYPE'
  | 'INVALID_VERIFICATION_TRANSITION'
  | 'FLAG_NOT_FOUND'
  | 'CPD_RECORD_NOT_FOUND'
  | 'CERTIFICATION_NOT_FOUND'
  | 'VERIFICATION_REQUEST_NOT_FOUND'
  | 'EMPLOYER_NOT_FOUND'
  | 'EMPLOYER_NOT_VERIFIED'
  | 'NDPA_CONSENT_REQUIRED'
  | 'JOB_POSTING_NOT_FOUND'
  | 'WRONG_EMPLOYER_TYPE'
  | 'ONBOARDING_INCOMPLETE'
  | 'PLACEMENT_NOT_FOUND'
  | 'SHORTLIST_NOT_FOUND'
  | 'REPLACEMENT_REQUEST_NOT_FOUND'
  | 'INVALID_PLACEMENT_TRANSITION'
  | 'PLACEMENT_ALREADY_ACTIVE'
  | 'PAYMENT_REQUIRED'
  | 'NO_ELIGIBLE_WORKERS'
  | 'INVOICE_NOT_FOUND'
  | 'SUBSCRIPTION_NOT_FOUND'
  | 'PAYMENT_PROVIDER_ERROR'
  | 'WEBHOOK_SIGNATURE_INVALID'
  | 'PIPELINE_CURRENCY_MISMATCH'
  | 'INVOICE_ALREADY_PAID'
  | 'AGENT_NOT_FOUND'
  | 'ASSIGNMENT_NOT_FOUND'
  | 'INVALID_ASSIGNMENT_TARGET'
  | 'NOTIFICATION_NOT_FOUND'
  | 'UNKNOWN_NOTIFICATION_KIND'
  | 'FORCED_KIND_CANNOT_BE_DISABLED'
  | 'EXPORT_TOO_LARGE'
  | 'NOTIFICATION_PROVIDER_ERROR'
  | 'CONTRACT_NOT_FOUND'
  | 'CONTRACT_TEMPLATE_NOT_FOUND'
  | 'WORKFORCE_CATEGORY_NOT_FOUND'
  | 'WORKFORCE_CATEGORY_SLUG_TAKEN'
  | 'CONTRACT_ALREADY_SIGNED'
  | 'CONTRACT_NOT_SIGNABLE'
  | 'CONTRACT_PARTY_MISMATCH'
  | 'CONTRACT_REAUTH_FAILED'
  | 'TEMPLATE_VARIABLE_MISSING'
  | 'COMPLAINT_NOT_FOUND'
  | 'COMPLAINT_NOT_ASSIGNABLE'
  | 'COMPLAINT_ALREADY_RESOLVED'
  | 'OFFER_NOT_FOUND'
  | 'OFFER_NOT_RESPONDABLE'
  | 'OFFER_DUPLICATE'
  | 'CONVERSATION_NOT_FOUND'
  | 'MESSAGE_NOT_VIEWABLE'
  | 'CONTACT_DETAILS_BLOCKED'
  | 'SAVED_SEARCH_NOT_FOUND'
  | 'INVALID_FILTER'
  | 'WELFARE_ESCALATION_NOT_FOUND'
  | 'WELFARE_REPORT_NOT_FOUND'
  | 'WELFARE_REPORT_UNAVAILABLE'
  | 'CONTRACT_NOT_AMENDABLE'
  | 'CONTRACT_AMENDMENT_NOT_FOUND'
  | 'RENEWAL_NOT_AVAILABLE'
  | 'JOB_POSTING_NOT_REVIEWABLE'
  | 'JOB_NOT_OPEN'
  | 'WORKER_NOT_ELIGIBLE'
  | 'ALREADY_APPLIED'
  | 'APPLICATION_NOT_FOUND'
  | 'INTERVIEW_NOT_FOUND'
  | 'INVALID_INTERVIEW_STATE';

export interface AppErrorInit {
  code: ErrorCode;
  message: string;
  statusCode: number;
  cause?: unknown;
  details?: Record<string, unknown>;
}

export class AppError extends Error {
  readonly code: ErrorCode;
  readonly statusCode: number;
  readonly details?: Record<string, unknown>;

  constructor(init: AppErrorInit) {
    super(init.message, { cause: init.cause });
    this.code = init.code;
    this.statusCode = init.statusCode;
    this.details = init.details;
    this.name = 'AppError';
  }

  toJSON() {
    return {
      error: {
        code: this.code,
        message: this.message,
        statusCode: this.statusCode,
        ...(this.details ? { details: this.details } : {}),
      },
    };
  }
}
