'use client';

import { Pencil, Users, XCircle } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { jobPostingCreateSchema, type JobPostingCreateInput } from '@oakvale/shared/schema/employer';
import {
  JOB_COUNTRIES,
  JOB_COUNTRY_LABELS,
  JOB_PRIORITY_LEVELS,
  JOB_SALARY_CURRENCIES,
  JOB_SALARY_CURRENCY_LABELS,
  JOB_SCHEDULES,
  JOB_VISIBILITY,
  locationOptionsForCountry,
  salaryBandsForCurrency,
} from '@oakvale/shared/enums/employer';
import { EmployerShell } from '@/components/dashboard/EmployerShell';
import { PageHeader } from '@/components/dashboard/Shell';
import { Table, THead, TBody, TR, TH, TD, TableEmpty } from '@/components/ui/Table';
import { IconButton } from '@/components/ui/IconButton';
import { Modal } from '@/components/ui/Modal';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { Input } from '@/components/ui/Input';
import { Pagination, usePagination } from '@/components/ui/Pagination';
import { Field, Select, Textarea } from '@/app/(worker)/worker/profile/SectionFrame';
import { ChipsInput } from '@/app/(worker)/worker/profile/sections/ChipsInput';
import { SpecialisationPicker } from '@/components/ui/SpecialisationPicker';
import { toast, toastApiError, toastFormErrors } from '@/lib/toast';
import { employersApi } from '@/lib/employers-api';
import { useHydratedTokens } from '@/lib/use-hydrated-tokens';
import { useEmployerConfig } from '@/lib/use-employer-config';

export function JobsListView() {
  const router = useRouter();
  const queryClient = useQueryClient();
  const hydrated = useHydratedTokens();
  const config = useEmployerConfig();
  const [showForm, setShowForm] = useState(false);

  const jobs = useQuery({
    queryKey: ['employerJobs'],
    queryFn: employersApi.listJobPostings,
    enabled: hydrated,
  });

  const close = useMutation({
    mutationFn: (id: string) => employersApi.closeJobPosting(id),
    onSuccess: () => {
      toast.success('Posting closed.');
      queryClient.invalidateQueries({ queryKey: ['employerJobs'] });
    },
    onError: (e) => toastApiError(e, 'Could not close the posting.'),
  });

  const pager = usePagination(jobs.data ?? []);

  return (
    <EmployerShell config={config}>
      <PageHeader
        eyebrow="Corporate · job postings"
        title="Open the door to placements."
        description="Each posting can be edited, closed, or filled. Shortlists are generated by your Oakvale agent."
        actions={<Button onClick={() => setShowForm(true)}>New posting</Button>}
      />

      <Modal
        open={showForm}
        onClose={() => setShowForm(false)}
        title="New Job Posting"
        description=""
        size="xl"
      >
        <JobPostingForm
          onCreated={() => { setShowForm(false); queryClient.invalidateQueries({ queryKey: ['employerJobs'] }); }}
          onCancel={() => setShowForm(false)}
        />
      </Modal>

      <Table>
        <THead>
          <TR>
            <TH>Title</TH>
            <TH>Status</TH>
            <TH>Openings</TH>
            <TH>Deadline</TH>
            <TH className="text-right">Actions</TH>
          </TR>
        </THead>
        <TBody>
          {pager.pageRows.map((j) => (
            <TR key={j.id} onClick={() => router.push(`/employer/jobs/${j.id}`)}>
              <TD className="font-medium">{j.title}</TD>
              <TD>
                <Badge tone={j.status === 'OPEN' ? 'sage' : j.status === 'CLOSED' ? 'neutral' : 'terracotta'}>
                  {j.status}
                </Badge>
              </TD>
              <TD className="tabular-nums">{j.openings}</TD>
              <TD muted>{j.deadline ?? '—'}</TD>
              <TD>
                <div className="flex items-center justify-end gap-1">
                  <IconButton
                    icon={Pencil}
                    label="Edit"
                    href={`/employer/jobs/${j.id}`}
                    onClick={(e) => e.stopPropagation()}
                  />
                  <IconButton
                    icon={Users}
                    label="Applicants"
                    href={`/employer/jobs/${j.id}/applicants`}
                    onClick={(e) => e.stopPropagation()}
                  />
                  {j.status !== 'CLOSED' ? (
                    <IconButton
                      icon={XCircle}
                      label="Close"
                      tone="danger"
                      onClick={(e) => {
                        e.stopPropagation();
                        close.mutate(j.id);
                      }}
                    />
                  ) : null}
                </div>
              </TD>
            </TR>
          ))}
          {(jobs.data ?? []).length === 0 ? (
            <TableEmpty colSpan={5}>No job postings yet.</TableEmpty>
          ) : null}
        </TBody>
      </Table>
      <Pagination state={pager} className="mt-4" />
    </EmployerShell>
  );
}

export function JobPostingForm({ onCreated, onCancel }: { onCreated: () => void; onCancel?: () => void }) {
  const hydrated = useHydratedTokens();
  const categories = useQuery({
    queryKey: ['workforceCategories'],
    queryFn: employersApi.listWorkforceCategories,
    enabled: hydrated,
  });
  const {
    register,
    handleSubmit,
    setValue,
    watch,
    formState: { errors, isSubmitting },
    reset,
  } = useForm<JobPostingCreateInput>({
    resolver: zodResolver(jobPostingCreateSchema),
    defaultValues: {
      priorityLevel: 'MEDIUM',
      status: 'OPEN',
      openings: 1,
      benefits: [],
      specialisations: [],
      backgroundCheckRequired: true,
      visibility: 'PUBLIC',
      country: 'NIGERIA',
      salaryCurrency: 'NGN',
    },
  });
  const v = watch();
  const mut = useMutation({
    mutationFn: employersApi.createJobPosting,
    onSuccess: () => {
      reset({
        priorityLevel: 'MEDIUM',
        status: 'OPEN',
        openings: 1,
        benefits: [],
        backgroundCheckRequired: true,
        visibility: 'PUBLIC',
        country: 'NIGERIA',
        salaryCurrency: 'NGN',
      });
      toast.success('Job posted.');
      onCreated();
    },
    onError: (e) => toastApiError(e, 'Could not post the job. Try again.'),
  });

  return (
    <form
      onSubmit={handleSubmit((vals) => mut.mutate(vals), toastFormErrors)}
      className="grid md:grid-cols-2 gap-4 mt-5"
    >
      <Field label="Title" required error={errors.title?.message}>
        <Input {...register('title')} />
      </Field>
      <Field label="Workforce category" required error={errors.workforceCategoryId?.message}>
        <Select
          {...register('workforceCategoryId')}
          options={[
            { value: '', label: 'Select a category…' },
            ...(categories.data ?? []).map((c) => ({ value: c.id, label: c.name })),
          ]}
        />
      </Field>
      <Field label="Visibility" required={false}>
        <Select
          {...register('visibility')}
          options={JOB_VISIBILITY.map((x) => ({
            value: x,
            label:
              x === 'PUBLIC'
                ? 'Public — searchable by all workers'
                : 'Restricted — notify matched workers',
          }))}
        />
      </Field>

      <Field label="Openings" required={false} error={errors.openings?.message}>
        <Input type="number" min={1} {...register('openings', { valueAsNumber: true })} />
      </Field>
      <Field label="Priority" required={false}>
        <Select
          {...register('priorityLevel')}
          options={JOB_PRIORITY_LEVELS.map((p) => ({ value: p, label: p.toLowerCase() }))}
        />
      </Field>
      <Field label="Country" required={false}>
        <Select
          {...register('country', {
            onChange: () => setValue('workLocation', '', { shouldDirty: true }),
          })}
          options={JOB_COUNTRIES.map((c) => ({ value: c, label: JOB_COUNTRY_LABELS[c] }))}
        />
      </Field>
      <Field label="Work location" required={false}>
        <Select
          {...register('workLocation')}
          options={[
            { value: '', label: 'Select a location…' },
            ...locationOptionsForCountry(v.country ?? 'NIGERIA').map((loc) => ({
              value: loc,
              label: loc,
            })),
          ]}
        />
      </Field>
      <Field label="Schedule" required={false}>
        <Select
          {...register('schedule')}
          options={[
            { value: '', label: 'Select a schedule…' },
            ...JOB_SCHEDULES.map((s) => ({ value: s, label: s })),
          ]}
        />
      </Field>
      <Field label="Salary currency" required={false}>
        <Select
          {...register('salaryCurrency', {
            onChange: () => setValue('salaryRange', '', { shouldDirty: true }),
          })}
          options={JOB_SALARY_CURRENCIES.map((c) => ({
            value: c,
            label: JOB_SALARY_CURRENCY_LABELS[c],
          }))}
        />
      </Field>
      <Field label="Salary range" required={false}>
        <Select
          {...register('salaryRange')}
          options={[
            { value: '', label: 'Select a range…' },
            ...salaryBandsForCurrency(v.salaryCurrency ?? 'NGN').map((b) => ({
              value: b,
              label: b,
            })),
          ]}
        />
      </Field>
      <Field label="Deadline" required={false}>
        <Input type="date" min={new Date().toISOString().slice(0, 10)} {...register('deadline')} />
      </Field>
      <div className="md:col-span-2">
        <Field label="Job Description" required error={errors.description?.message}>
          <Textarea {...register('description')} />
        </Field>
      </div>
      <div className="md:col-span-2">
        <Field label="Duties" required={false}>
          <Textarea {...register('duties')} />
        </Field>
      </div>
     
      <div className="md:col-span-2">
        <Field label="Benefits" required={false}>
          <ChipsInput
            value={v.benefits ?? []}
            onChange={(next) => setValue('benefits', next, { shouldDirty: true })}
            placeholder="e.g. HMO, Stipend, Training"
          />
        </Field>
      </div>
      <div className="md:col-span-2">
        <Field
          label="Care specialisations"
          required={false}
          hint="Tick the care tasks this role involves — caregivers see these when applying."
        >
          <SpecialisationPicker
            value={v.specialisations ?? []}
            onChange={(next) => setValue('specialisations', next, { shouldDirty: true })}
          />
        </Field>
      </div>
      <div>
        <Field label="Background check required" required={false}>
          <label className="flex items-center gap-2 text-sm text-ink-600">
            <input type="checkbox" {...register('backgroundCheckRequired')} />
            Require a clear background check for this role
          </label>
        </Field>
      </div>
      <div className="md:col-span-2 flex justify-end gap-3">
        {onCancel ? (
          <Button type="button" variant="outline" onClick={onCancel} disabled={mut.isPending}>
            Cancel
          </Button>
        ) : null}
        <Button type="submit" disabled={isSubmitting || mut.isPending}>
          {mut.isPending ? 'Posting…' : 'Post job'}
        </Button>
      </div>
    </form>
  );
}
