'use client';

import Link from 'next/link';
import { TextLink } from '@/components/ui/Link';
import { ArrowLeft } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { EmployerShell } from '@/components/dashboard/EmployerShell';
import { PageHeader } from '@/components/dashboard/Shell';
import { SubscribeBanner } from '@/components/ui/SubscribeBanner';
import { Card, CardEyebrow, CardTitle } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { placementsApi } from '@/lib/placements-api';
import { useHydratedTokens } from '@/lib/use-hydrated-tokens';
import { useEmployerConfig } from '@/lib/use-employer-config';

export function ShortlistsList() {
  const hydrated = useHydratedTokens();
  const config = useEmployerConfig();

  const q = useQuery({
    queryKey: ['employerShortlists'],
    queryFn: placementsApi.employerShortlists,
    enabled: hydrated,
  });

  return (
    <EmployerShell config={config}>
      <Link
        href="/employer/dashboard"
        className="mb-4 inline-flex items-center gap-2 rounded-full border border-ink/12 bg-white px-4 h-9 text-sm font-medium text-ink transition hover:border-brand-500/40 hover:bg-cream-50"
      >
        <ArrowLeft className="h-4 w-4" aria-hidden />
        Back
      </Link>
      <PageHeader
        eyebrow="Diaspora · shortlists"
        title="Your shortlists."
        description="Each shortlist is generated by our agents from the latest care assessment. Open the most recent to choose a carer."
      />

      <SubscribeBanner surface="shortlist" />

      <div className="grid md:grid-cols-2 gap-5">
        {(q.data ?? []).map((s) => (
          <Card key={s.id}>
            <div className="flex items-center justify-between gap-3">
              <CardEyebrow>Shortlist · {s.requestType.toLowerCase()}</CardEyebrow>
              <Badge tone={s.decidedAt ? 'sage' : s.viewedAt ? 'neutral' : 'terracotta'}>
                {s.decidedAt ? 'Decided' : s.viewedAt ? 'Open' : 'New'}
              </Badge>
            </div>
            <CardTitle>{s.workerIds.length} candidates</CardTitle>
            <p className="text-sm text-muted mt-2">
              Generated {new Date(s.createdAt).toLocaleString()}
              {s.expiresAt ? ` · expires ${new Date(s.expiresAt).toLocaleDateString()}` : ''}
            </p>
            <div className="mt-4">
              <TextLink href={`/employer/shortlist/${s.id}`}>
                Open shortlist →
              </TextLink>
            </div>
          </Card>
        ))}
        {q.isSuccess && (q.data ?? []).length === 0 ? (
          <Card className="md:col-span-2 text-muted text-sm text-center">
            No shortlists yet. Our agents will generate one once your assessment is complete.
          </Card>
        ) : null}
      </div>
    </EmployerShell>
  );
}
